project:
  type: website

website:
  title: "Palaeoverse"
  image: /images/logo.png
  favicon: /images/logo.png
  navbar:
    left:
      - href: index.qmd
        text: Overview
      - about.qmd
      - href: package.qmd
        text: R Packages
      - href: directory.qmd
        text: Directory
      - resources.qmd
      - community.qmd

format:
  html:
    theme:
      - cosmo
    linkcolor: "#0D725A"
    link-external-icon: false
    link-external-newwindow: true
    css: styles.css
    toc: true
    toc-depth: 3

editor: visual

