project:
  type: website

website:
  title: "Palaeoverse"
  image: /images/palaeoverse-pkg.png
  favicon: /images/palaeoverse-pkg.png
  twitter-card:
    creator: "@LewisAlanJones"
    site: "@ThePalaeoverse"
  open-graph: true
  page-footer: 
    left: "Copyright 2022, Lewis A. Jones" 
    right: 
      - icon: github
        href: https://github.com/palaeoverse-community
      - icon: twitter 
        href: https://twitter.com/ThePalaeoverse
  navbar:
    left:
      - href: index.qmd
        text: Overview
      - about.qmd
      - href: package.qmd
        text: R Packages
      - href: directory.qmd
        text: Directory
      - resources.qmd
      - community.qmd

format:
  html:
    theme:
      - pulse
    link-external-icon: false
    link-external-newwindow: true
    css: styles.css
    toc: true
    toc-depth: 3

editor: visual

